---
- hosts: all
  become: yes
  become_user: root

  vars:
    mysql_root_password: password
    phpmyadmin_config_file: /etc/phpMyAdmin/config.inc.php
    phpmyadmin_blowfish_secret: Vq8HIZnY6hl2XQgLu9U83k62XMO7Jf9s

  tasks:

    # install packages

    - name: Install yum packages
      yum: name={{ item }} state=latest
      with_items:
        - mariadb
        - mariadb-server
        - nginx
        - php56-php
        - php56-php-cli
        - php56-php-fpm
        - php56-php-gd
        - php56-php-mbstring
        - php56-php-mcrypt
        - php56-php-mysql
        - php56-php-pdo
        - php56-php-pecl-xdebug
        - php72-php
        - php72-php-cli
        - php72-php-fpm
        - php72-php-gd
        - php72-php-mbstring
        - php72-php-mcrypt
        - php72-php-mysql
        - php72-php-pdo
        - php72-php-pecl-xdebug
        - phpMyAdmin
        - MySQL-python

    # configure php56

    - name: Update php-fpm user to nginx
      replace: path=/opt/remi/php56/root/etc/php-fpm.d/www.conf regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
        - { regexp: '^(user|group) = apache$', replace: '\1 = nginx' }
        - { regexp: '^(listen) = .+',          replace: '\1 = 127.0.0.1:9056' }

    - name: Update php.ini
      replace: path=/opt/remi/php56/root/etc/php.ini regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
        - { regexp: '^(error_reporting) = .+',     replace: '\1 = E_ALL & ~E_NOTICE & ~E_STRICT' }
        - { regexp: '^(display_errors) = .+',      replace: '\1 = On' }
        - { regexp: '^(html_errors) = .+',         replace: '\1 = On' }
        - { regexp: '^(post_max_size) = .+',       replace: '\1 = 1024M' }
        - { regexp: '^(upload_max_filesize) = .+', replace: '\1 = 1024M' }

    - name: Set php session folder permission
      file: path=/opt/remi/php56/root/var/lib/php/session owner=root group=nginx state=directory mode=0770

    # configure php72

    - name: Update php-fpm user to nginx
      replace: path=/etc/opt/remi/php72/php-fpm.d/www.conf regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
        - { regexp: '^(user|group) = apache$', replace: '\1 = nginx' }
        - { regexp: '^(listen) = .+',          replace: '\1 = 127.0.0.1:9072' }

    - name: Update php.ini
      replace: path=/etc/opt/remi/php72/php.ini regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
        - { regexp: '^(error_reporting) = .+',     replace: '\1 = E_ALL & ~E_NOTICE & ~E_STRICT' }
        - { regexp: '^(display_errors) = .+',      replace: '\1 = On' }
        - { regexp: '^(html_errors) = .+',         replace: '\1 = On' }
        - { regexp: '^(post_max_size) = .+',       replace: '\1 = 1024M' }
        - { regexp: '^(upload_max_filesize) = .+', replace: '\1 = 1024M' }

    - name: Set php session folder permission
      file: path=/var/opt/remi/php72/lib/php/session owner=root group=nginx state=directory mode=0770

    # configure nginx

    - name: Get nginx-wwwroot config
      copy: src=/vagrant/config/{{ item }} dest=/etc/nginx/conf.d/{{ item }} owner=root group=root mode=0644
      with_items:
        - nginx-wwwroot.conf
        - nginx-phpmyadmin.conf

    - name: Get nginx-wwwroot config
      copy: src=/vagrant/config/{{ item }} dest=/etc/nginx/certs/{{ item }} owner=root group=root mode=0640
      with_items:
        - nginx-selfsigned.crt
        - nginx-selfsigned.key

    # configure phpMyAdmin

    - name: Configure phpMyAdmin config directory permission
      file: path=/etc/phpMyAdmin owner=root group=nginx state=directory mode=0750

    - name: Configure phpMyAdmin config file permission
      file: path={{ phpmyadmin_config_file }} owner=root group=nginx state=file mode=0640

    - name: Configure phpMyAdmin config file link
      file: src={{ phpmyadmin_config_file }} dest=/usr/share/phpMyAdmin/config.inc.php state=link owner=root group=root

    - name: Configure phpMyAdmin file
      replace:
        path: '{{ phpmyadmin_config_file }}'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
        - { regexp: "^(.+\\['blowfish_secret'\\])\\s+=\\s+.+$", replace: "\\1 = '{{ phpmyadmin_blowfish_secret }}';"}
        - { regexp: "^(.+\\['controluser'\\])\\s+=\\s+.+$",     replace: "\\1 = 'root';"}
        - { regexp: "^(.+\\['controlpass'\\])\\s+=\\s+.+$",     replace: "\\1 = '{{ mysql_root_password }}';"}
        - { regexp: "^(.+\\['pmadb'\\])\\s+=\\s+.+$",           replace: "\\1 = 'phpmyadmin';"}
        - { regexp: "^(.+\\['bookmarktable'\\])\\s+=\\s+.+$",   replace: "\\1 = 'pma__bookmark';"}
        - { regexp: "^(.+\\['column_info'\\])\\s+=\\s+.+$",     replace: "\\1 = 'pma__column_info';"}
        - { regexp: "^(.+\\['history'\\])\\s+=\\s+.+$",         replace: "\\1 = 'pma__history';"}
        - { regexp: "^(.+\\['pdf_pages'\\])\\s+=\\s+.+$",       replace: "\\1 = 'pma__pdf_pages';"}
        - { regexp: "^(.+\\['relation'\\])\\s+=\\s+.+$",        replace: "\\1 = 'pma__relation';"}
        - { regexp: "^(.+\\['table_coords'\\])\\s+=\\s+.+$",    replace: "\\1 = 'pma__table_coords';"}
        - { regexp: "^(.+\\['table_info'\\])\\s+=\\s+.+$",      replace: "\\1 = 'pma__table_info';"}
        - { regexp: "^#*(.+\\['PmaNoRelation_DisableWarning'\\]\\s+=\\s+.+)$", replace: "#\\1"}

    - name: Remove ending php tag
      lineinfile:
        path: '{{ phpmyadmin_config_file }}'
        regexp: '\?>'
        state: absent

    - name: Add missing phpMyAdmin configs
      lineinfile:
        path: '{{ phpmyadmin_config_file }}'
        line: '{{ item }}'
      with_items:
        - "$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';"
        - "$cfg['Servers'][$i]['favorite'] = 'pma__favorite';"
        - "$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';"
        - "$cfg['Servers'][$i]['recent'] = 'pma__recent';"
        - "$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';"
        - "$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';"
        - "$cfg['Servers'][$i]['tracking'] = 'pma__tracking';"
        - "$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';"
        - "$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';"
        - "$cfg['Servers'][$i]['users'] = 'pma__users';"

    # enable services

    - name: Enable php-fpm nginx mariadb
      systemd: name={{ item }} enabled=true
      with_items:
        - php56-php-fpm
        - php72-php-fpm
        - nginx
        - mariadb

    # start services

    - name: Restart php-fpm nginx mariadb
      systemd: name={{ item }} state=restarted
      with_items:
        - php56-php-fpm
        - php72-php-fpm
        - nginx
        - mariadb
      changed_when: false

    # secure mysql

    - name: Set root Password
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
      with_items:
        - localhost

    - name: Add .my.cnf
      template: src=/vagrant/config/my.cnf dest=/root/.my.cnf owner=root group=root mode=0600

    - name: Set other root passwords on localhost
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
      with_items:
        - 127.0.0.1
        - ::1

    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: false

    - name: Remove anonymous users
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User=''
      changed_when: false

    - name: Disallow root login remotely
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: false

    - name: Remove test database and access to it
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DROP DATABASE test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: false
      ignore_errors: true

    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: false

    # configure phpMyAdmin database

    - name: Configure phpMyAdmin database
      shell: 'mysql < /usr/share/phpMyAdmin/sql/create_tables.sql'
      changed_when: false